---
- ansible.builtin.include_tasks: install.yml
  tags:
    - acme_sh_install

- ansible.builtin.include_tasks: logging.yml
  tags:
    - acme_sh_logging
  when: acme_sh_logging

- ansible.builtin.include_tasks: notify.yml
  tags:
    - acme_sh_notify
  when: acme_sh_notify

- ansible.builtin.include_tasks: manage.yml
  tags:
    - acme_sh_manage
